name: dimensions_theme
description: A theme extension to define app dimensions such as blank spaces or paddings inside your theme.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.16.0

flutter: